test:
  extends:
    file: docker-compose.yml
    service: api
  links:
    - db
  command:
    npm run wait-n-jenkins
  environment:
    PGHOST: db
    TEST_OUTPUT_PATH: /tmp/jenkins
  volumes:
    - $WORKSPACE:/tmp/jenkins

db:
  extends:
    file: docker-compose-local.yml
    service: db
