api:
  extends:
    file: docker-compose.yml
    service: api
  ports:
    - "4747:4747"
  links:
    - db
  environment:
    PORT: 4747
    PGHOST: db

db:
  build: ./postgres/
  environment:
    POSTGRES_PASSWORD: GCTORSTORAGEMASTER
    POSTGRES_USER: postgres
