test:
  extends:
    file: docker-compose.yml
    service: webapp
  build: .
  links:
    - db
    - redis
  command:
    npm run test-jenkins
  environment:
    PGHOST: db
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 1
    EMAIL: 0
    VERBOSE_REQUEST_LOGS: 0
    TEST_OUTPUT_PATH: /tmp/jenkins

db:
  extends:
    file: docker-compose-local.yml
    service: db

redis:
  extends:
    file: docker-compose-local.yml
    service: redis
