webapp:
  extends:
    file: docker-compose.yml
    service: webapp
  build: .
  links:
    - db
    - redis
  command:
    npm run start-instance
  ports:
    - "3000:3000"
  environment:
    PORT: 3000
    PGHOST: db
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 1
    HOST_URL: http://localhost:3000

db:
  extends:
    file: ./storage-ext/docker-compose-local.yml
    service: db
  build: ./storage-ext/postgres/

redis:
  restart: always
  image: redis:3.2.0-alpine
  command: redis-server /usr/local/etc/redis/redis.conf
  volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
