webapp:
  extends:
    file: docker-compose-aws.yml
    service: webapp
  image: quay.io/bionano/gctor_webapp${BNR_ENV_TAG}
  ports:
    - "3000"
  environment:
    PORT: 3000
  mem_limit: 10737418240 # 10 GB RAM for gc docker stats as of 22-Mar-17 show max mem usage of 6.5 GB in dev
