webapp:
  extends:
    file: docker-compose.yml
    service: webapp
  image: quay.io/bionano/gctor_webapp${BNR_ENV_TAG}
  environment:
    EMAIL: 1
    #lb dns names always have the environment included
    STORAGE_API: http://internal-lb.${BNR_ENVIRONMENT}.bionano.bio:4747/api
    API_END_POINT: http://internal-lb.${BNR_ENVIRONMENT}.bionano.bio:8080/api
    HOST_URL: https://geneticconstructor${BNR_ENV_URL_SUFFIX}.bionano.autodesk.com
    BNR_ENVIRONMENT: ${BNR_ENVIRONMENT}
    BNR_ENV_TAG: ${BNR_ENV_TAG}
    BNR_ENV_URL_SUFFIX: ${BNR_ENV_URL_SUFFIX}
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PORT: ${REDIS_PORT}
    REDIS_DB: ${REDIS_DB}
    BLAST_URL: ${BLAST_URL}
  command:
    npm run server-auth
  log_driver: json-file
  restart: always
