batch:
  extends:
    file: docker-compose-aws.yml
    service: webapp
  image: quay.io/autodesk_bionano/gctor_webapp${BNR_ENV_TAG}
#  image: geneticconstructor_webapp:latest # local build
  environment:
    DEBUG: constructor:data:*
  command:
    ./bin/migrate/infinite-loop.sh
